[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
[templates.kitty]
input_path = "/home/hinne/.config/noctalia/kitty.conf.template"
output_path = "/home/hinne/.config/kitty/noctalia-colors.conf"
post_hook = "kitty @ set-colors -a -c /home/hinne/.config/kitty/noctalia-colors.conf"
