# This is your home-manager configuration file
# Use this to configure your home environment (it replaces ~/.config/nixpkgs/home.nix)
{ inputs
, lib
, config
, pkgs
, ...
}: {
  # You can import other home-manager modules here
  imports = [
    # If you want to use home-manager modules from other flakes (such as nix-colors):
    # inputs.nix-colors.homeManagerModule

    # You can also split up your configuration and import pieces of it here:
    ./kitty.nix
    ./zsh.nix
    ./starship.nix
    ./git.nix
    ./scripts.nix
    ./tools.nix
    ./niri.nix
    ./noctalia.nix
    ./fcitx5.nix
  ];

  nixpkgs = {
    # You can add overlays here
    overlays = [
      # If you want to use overlays exported from other flakes:
      # neovim-nightly-overlay.overlays.default

      # Or define it inline, for example:
      # (final: prev: {
      #   hi = final.hello.overrideAttrs (oldAttrs: {
      #     patches = [ ./change-hello-to-hi.patch ];
      #   });
      # })
    ];
    # Configure your nixpkgs instance
    config = {
      # Disable if you don't want unfree packages
      allowUnfree = true;
    };
  };

  # TODO: Set your username
  home = {
    username = "hinne";
    homeDirectory = "/home/hinne";
  };

  # Environment Variables
  home.sessionVariables = {
    PNPM_HOME = "$HOME/.local/share/pnpm";
    EDITOR = "nvim";
    TERMINAL = "kitty";
  };

  # Tạo Desktop Entry đè lên mặc định để sửa lỗi launcher/file search
  xdg.desktopEntries = {
    yazi = {
      name = "Yazi";
      exec = "kitty -e yazi %u";
      terminal = false;
      categories = [ "System" "FileTools" "FileManager" "ConsoleOnly" ];
      mimeType = [ "inode/directory" ];
    };
    nvim = {
      name = "Neovim";
      exec = "kitty -e nvim %F";
      terminal = false;
      categories = [ "Utility" "TextEditor" ];
      mimeType = [ "text/plain" ];
    };
  };

  home.sessionPath = [
    "$HOME/.local/share/pnpm/bin"
    "$HOME/.local/share/pnpm"
    "$HOME/.local/bin"
  ];

  # Add stuff for your user as you see fit:
  home.packages = with pkgs; [
    # Shell + Terminal (Managed via native modules in zsh.nix, kitty.nix, tools.nix)
    neovim
    fastfetch
    pnpm

    # Font
    nerd-fonts.jetbrains-mono

    # Desktop shell, WM
    niri
    xwayland-satellite
    matugen

    # General Apps
    vesktop
    telegram-desktop
    obs-studio
    localsend
    obsidian
    libreoffice
    onlyoffice-desktopeditors
    mpv
    imv
    upscayl
    evtest
    wl-clipboard
    stremio-linux-shell
    inputs.thorium.packages.${pkgs.system}.thorium-avx2

    # Yazi Dependencies
    poppler-utils
    xlsx2csv
    libreoffice
    ffmpegthumbnailer
    ffmpeg
    mediainfo
    unar
    p7zip
    zip
    (python3.withPackages (p: [ p.rich p.docx2txt ]))

    # Text Editor + IDE
    neovim
    gcc
    gnumake
    ripgrep
    fd
    unzip
    jetbrains-toolbox
    jetbrains.datagrip
    jetbrains.idea
    jetbrains.webstorm
    zed-editor

    # Antigravity từ Nix flake
    inputs.antigravity.packages.${pkgs.system}.google-antigravity-cli
  ];

  # Enable home-manager
  programs.home-manager.enable = true;

  # Automount USB drives
  services.udiskie.enable = true;

  xdg.configFile = {
    "nvim" = {
      source = ./nvim;
      recursive = true;
    };
    "mpv".source = ./mpv;
    "matugen/config.toml".text = ''
      [config]
      wallpaper_dir = "/home/hinne/Pictures/Wallpapers"
      
      [templates.nvim]
      input_path = "/home/hinne/.config/matugen/templates/nvim.lua"
      output_path = "/home/hinne/.cache/nvim/matugen.lua"

      [templates.kitty]
      input_path = "/home/hinne/.config/matugen/templates/kitty.conf"
      output_path = "/home/hinne/.config/kitty/themes/noctalia.conf"
    '';
    "matugen/templates/kitty.conf".text = ''
      # Generated by Matugen
      foreground {{colors.on_surface.default.hex}}
      background {{colors.surface.default.hex}}
      selection_foreground {{colors.on_secondary.default.hex}}
      selection_background {{colors.secondary_fixed_dim.default.hex}}
      cursor {{colors.on_surface.default.hex}}
      cursor_text_color {{colors.surface.default.hex}}
      active_tab_foreground {{colors.on_secondary_container.default.hex}}
      active_tab_background {{colors.secondary_container.default.hex}}
      inactive_tab_foreground {{colors.on_surface_variant.default.hex}}
      inactive_tab_background {{colors.surface_container_low.default.hex}}
      active_border_color {{colors.primary.default.hex}}
      inactive_border_color {{colors.outline_variant.default.hex}}

      color0 {{colors.surface.default.hex}}
      color8 {{colors.surface_variant.default.hex}}
      color1 {{colors.error.default.hex}}
      color9 {{colors.error.default.hex}}
      color2 {{colors.primary.default.hex}}
      color10 {{colors.primary.default.hex}}
      color3 {{colors.tertiary.default.hex}}
      color11 {{colors.tertiary.default.hex}}
      color4 {{colors.secondary.default.hex}}
      color12 {{colors.secondary.default.hex}}
      color5 {{colors.primary.default.hex}}
      color13 {{colors.primary.default.hex}}
      color6 {{colors.secondary.default.hex}}
      color14 {{colors.secondary.default.hex}}
      color7 {{colors.on_surface.default.hex}}
      color15 {{colors.on_surface.default.hex}}
    '';
    "matugen/templates/nvim.lua".text = ''
      require('base16-colorscheme').setup({
        base00 = '{{colors.surface.default.hex}}',
        base01 = '{{colors.surface_dim.default.hex}}',
        base02 = '{{colors.surface_container.default.hex}}',
        base03 = '{{colors.outline_variant.default.hex}}',
        base04 = '{{colors.outline.default.hex}}',
        base05 = '{{colors.on_surface_variant.default.hex}}',
        base06 = '{{colors.on_surface.default.hex}}',
        base07 = '{{colors.on_surface.default.hex}}',
        base08 = '{{colors.error.default.hex}}',
        base09 = '{{colors.tertiary.default.hex}}',
        base0A = '{{colors.primary.default.hex}}',
        base0B = '{{colors.secondary.default.hex}}',
        base0C = '{{colors.tertiary.default.hex}}',
        base0D = '{{colors.primary.default.hex}}',
        base0E = '{{colors.secondary.default.hex}}',
        base0F = '{{colors.error.default.hex}}',
      })
      local hi = function(group, opts)
        vim.api.nvim_set_hl(0, group, opts)
      end
      
      -- Enable Transparency to seamlessly match Kitty's background
      hi('Normal', { bg = 'NONE' })
      hi('NormalNC', { bg = 'NONE' })
      hi('SignColumn', { bg = 'NONE' })
      hi('EndOfBuffer', { bg = 'NONE' })
      hi('NeoTreeNormal', { bg = 'NONE' })
      hi('NeoTreeNormalNC', { bg = 'NONE' })
      hi('NeoTreeWinSeparator', { fg = '{{colors.outline_variant.default.hex}}', bg = 'NONE' })
      hi('WinSeparator', { fg = '{{colors.outline_variant.default.hex}}', bg = 'NONE' })

      hi('TelescopeNormal',         { fg = '{{colors.on_surface.default.hex}}', bg = 'NONE' })
      hi('TelescopeBorder',         { fg = '{{colors.outline_variant.default.hex}}', bg = 'NONE' })
      hi('TelescopePromptNormal',   { fg = '{{colors.on_surface.default.hex}}', bg = 'NONE' })
      hi('TelescopePromptBorder',   { fg = '{{colors.outline_variant.default.hex}}', bg = 'NONE' })
      hi('TelescopePromptPrefix',   { fg = '{{colors.primary.default.hex}}', bg = 'NONE' })
      hi('TelescopePromptCounter',  { fg = '{{colors.outline.default.hex}}', bg = 'NONE' })
      hi('TelescopePromptTitle',    { fg = '{{colors.surface.default.hex}}', bg = '{{colors.primary.default.hex}}' })
      hi('TelescopePreviewTitle',   { fg = '{{colors.surface.default.hex}}', bg = '{{colors.secondary.default.hex}}' })
      hi('TelescopeResultsTitle',   { fg = '{{colors.surface.default.hex}}', bg = '{{colors.tertiary.default.hex}}' })
      hi('TelescopeSelection',      { fg = '{{colors.on_surface.default.hex}}', bg = '{{colors.surface_container.default.hex}}' })
      hi('TelescopeSelectionCaret', { fg = '{{colors.primary.default.hex}}', bg = '{{colors.surface_container.default.hex}}' })
      hi('TelescopeMatching',       { fg = '{{colors.primary.default.hex}}', bold = true })
    '';
  };

  # Sops-Nix configuration for secrets
  sops = {
    age.keyFile = "${config.home.homeDirectory}/.config/sops/age/keys.txt"; # Phải trỏ đúng file chứa key
    defaultSopsFile = ../secrets/secrets.yaml;
    secrets."ssh_key" = {
      path = "${config.home.homeDirectory}/.ssh/id_ed25519";
    };
  };

  # Default applications
  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "text/html" = "thorium-browser.desktop";
      "x-scheme-handler/http" = "thorium-browser.desktop";
      "x-scheme-handler/https" = "thorium-browser.desktop";
      "x-scheme-handler/about" = "thorium-browser.desktop";
      "x-scheme-handler/unknown" = "thorium-browser.desktop";

      # File Manager
      "inode/directory" = "yazi.desktop";

      # Image Viewer
      "image/jpeg" = "imv.desktop";
      "image/png" = "imv.desktop";
      "image/gif" = "imv.desktop";
      "image/webp" = "imv.desktop";

      # Video Player
      "video/mp4" = "mpv.desktop";
      "video/mkv" = "mpv.desktop";
      "video/x-matroska" = "mpv.desktop";
      "video/webm" = "mpv.desktop";

      # Text Editor
      "text/plain" = "nvim.desktop";
      "text/markdown" = "nvim.desktop";
    };
  };


  # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
  home.stateVersion = "25.11";

  # Enable font discovery for home-manager fonts
  fonts.fontconfig.enable = true;
}
